[env:rp2040-gateway-node]
platform = raspberrypi
board = pico
framework = arduino

lib_extra_dirs = ../../../protocol

build_flags =
    -D ORN_TARGET_RP2040
    -D ORN_ROLE_GATEWAY
    -Wall
    -Wextra

monitor_speed = 115200